### ISSUE TITLE
Cannot run on Ubuntu bionic: libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by probonopd** [liquidev/netcanv#37]
Was built on a too new system and hence cannot run on Ubuntu bionic:

> AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/firejail/appimage/.appimage-9561/AppRun)

Reference:
https://github.com/AppImage/appimage.github.io/pull/2754

**Comment by liquidev** [comment]
I suppose you're using the versions built using CI?

**Comment by liquidev** [comment]
If so, I have just updated the CI to build on Ubuntu 18.04, and made a new release built on that. I don't have a Ubuntu 18.04 machine, so please check if it works fine now.

**Comment by probonopd** [comment]
Thanks @liquidev, will re-run the test at https://github.com/AppImage/appimage.github.io/pull/2754.

**Comment by liquidev** [comment]
This is fixed already, and the build fails for a different reason. Closing.
