### ISSUE TITLE
Shortcut for changing brush size

### ISSUE THREAD

**Issue by Ezioleq** [liquidev/netcanv#51]
Changing the brush size is currently a bit cumbersome. I'd suggest giving the option to resize the brush with some keyboard shortcut, such as `Ctrl` + `Scroll` or a dedicated shortcut `Ctrl` + `+`/`-`. Also, we could add the ability to change the brush size with the scroll wheel whenever the cursor is over the size bar.

**Comment by liquidev** [comment]
I opt for <kbd>Shift</kbd> + Scroll, as well as just <kbd>-</kbd> and <kbd>=</kbd> (next to the numbers row) alone for ergonomics sake. This way you don't need to stretch your fingers across the keyboard to change the brush size; you always press just one key. The <kbd>-</kbd> and <kbd>=</kbd> keys are included for touchpad-friendliness as scrolling can be a bit cumbersome there. I feel like touchpad support is an area NetCanv could use some improvement in.

**Comment by liquidev** [comment]
The final choices are:

- <kbd>Ctrl</kbd> + <kbd>Scroll ↓</kbd>, or <kbd>[</kbd> - decrease
- <kbd>Ctrl</kbd> + <kbd>Scroll ↑</kbd>, or <kbd>]</kbd> - increase

The bracket shortcuts are inherited from Krita, which NetCanv used as a model for navigation.
