### ISSUE TITLE
Do not overwrite the configuration file if one field is simply missing

### ISSUE THREAD

**Issue by devildefu** [liquidev/netcanv#55]
If one field is missing from the configuration file then netcanv decides to overwrite it:
```
error while deserializing config file: missing field `toolbar_position` for key `ui` at line 5 column 1
falling back to default config
the user config will be overwritten with a fresh one
```

Over time there will be more and more options and missing one will immediately remove all the others. For the current amount this is acceptable, but with each subsequent update this configuration file will be overwritten and each option will need to be restored (and we are not Windows). It will be better to overwrite only non-existent fields instead of all fields.

**Comment by liquidev** [comment]
Fixed in a958bb9.
